#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "input_data.h"   // contains unsigned char input_bin[] and input_bin_len

// -----------------------------------------------------------------------------
// Memref descriptors (must match the ABI used by the MLIR → LLVM lowering)
// -----------------------------------------------------------------------------
typedef struct {
  int8_t *allocated;
  int8_t *aligned;
  int64_t offset;
  int64_t sizes[2];
  int64_t strides[2];
} memref2d_i8;

typedef struct {
  int32_t *allocated;
  int32_t *aligned;
  int64_t offset;
  int64_t sizes[2];
  int64_t strides[2];
} memref2d_i32;

// -----------------------------------------------------------------------------
// Cycle counter for RISC‑V
// -----------------------------------------------------------------------------
static uint64_t read_cycles(void) {
    uint64_t cycles;
    asm volatile ("rdcycle %0" : "=r" (cycles));
    return cycles;
}

// -----------------------------------------------------------------------------
// External MLIR function (the lowered forward pass)
// -----------------------------------------------------------------------------
extern memref2d_i32 forward(int8_t *input_allocated, int8_t *input_aligned,
                            int64_t input_offset, int64_t input_size0,
                            int64_t input_size1, int64_t input_stride0,
                            int64_t input_stride1);

// -----------------------------------------------------------------------------
// Create a 2D memref for int8 data (row‑major)
// -----------------------------------------------------------------------------
memref2d_i8 create_memref_i8(int64_t rows, int64_t cols, const int8_t *data) {
  memref2d_i8 mem;
  mem.allocated = (int8_t *)malloc(rows * cols * sizeof(int8_t));
  mem.aligned = mem.allocated;
  mem.offset = 0;
  mem.sizes[0] = rows;
  mem.sizes[1] = cols;
  // Row‑major stride: row_stride = cols, col_stride = 1
  mem.strides[0] = cols;
  mem.strides[1] = 1;
  if (data) {
    memcpy(mem.allocated, data, rows * cols * sizeof(int8_t));
  } else {
    memset(mem.allocated, 0, rows * cols * sizeof(int8_t));
  }
  return mem;
}

// -----------------------------------------------------------------------------
// Free memref memory
// -----------------------------------------------------------------------------
void free_memref_i8(memref2d_i8 *mem) {
  if (mem->allocated) {
    free(mem->allocated);
    mem->allocated = NULL;
    mem->aligned = NULL;
  }
}

void free_memref_i32(memref2d_i32 *mem) {
  if (mem->allocated) {
    free(mem->allocated);
    mem->allocated = NULL;
    mem->aligned = NULL;
  }
}

// -----------------------------------------------------------------------------
// Main: use embedded quantized image, run inference, print result
// -----------------------------------------------------------------------------
int main(int argc, char *argv[]) {
  const int64_t BATCH = 1;
  const int64_t IN_FEATURES = 784;   // 28×28
  const int64_t OUT_FEATURES = 10;   // digits 0-9

  // Use the embedded image data generated by xxd -i
  // input_bin is unsigned char, but the model expects int8.
  // Two's complement representation is identical, so we cast.
  const int8_t *input_data = (const int8_t*)input_bin;

  // Sanity check: ensure the embedded data has the correct length
  if (input_bin_len != BATCH * IN_FEATURES) {
    fprintf(stderr, "Error: embedded image size mismatch (%u vs %llu)\n",
            input_bin_len, (unsigned long long)(BATCH * IN_FEATURES));
    return 1;
  }

  // -------------------------------------------------------------------------
  // Create memref and call MLIR function with cycle counting
  // -------------------------------------------------------------------------
  memref2d_i8 input_mem = create_memref_i8(BATCH, IN_FEATURES, input_data);

  uint64_t start_cycles = read_cycles();
  memref2d_i32 output_mem = forward(
      input_mem.allocated, input_mem.aligned, input_mem.offset,
      input_mem.sizes[0], input_mem.sizes[1],
      input_mem.strides[0], input_mem.strides[1]);
  uint64_t end_cycles = read_cycles();

  uint64_t cycles_taken = end_cycles - start_cycles;
  printf("Inference took %llu cycles\n", cycles_taken);

  // -------------------------------------------------------------------------
  // Print output logits (int32)
  // -------------------------------------------------------------------------
  printf("Output logits (int32):\n");
  for (int64_t c = 0; c < OUT_FEATURES; ++c) {
    int64_t idx = output_mem.offset + c * output_mem.strides[1];
    printf("%d ", output_mem.aligned[idx]);
  }
  printf("\n");

  // Find predicted class (argmax)
  int32_t max_val = output_mem.aligned[output_mem.offset];
  int max_idx = 0;
  for (int64_t c = 1; c < OUT_FEATURES; ++c) {
    int64_t idx = output_mem.offset + c * output_mem.strides[1];
    if (output_mem.aligned[idx] > max_val) {
      max_val = output_mem.aligned[idx];
      max_idx = c;
    }
  }
  printf("Predicted digit: %d\n", max_idx);

  // -------------------------------------------------------------------------
  // Cleanup
  // -------------------------------------------------------------------------
  free_memref_i8(&input_mem);
  free_memref_i32(&output_mem);

  return 0;
}